name: Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Test Package bruno-query
        run: npm run test --workspace=packages/bruno-query
      - name: Build Package bruno-query
        run: npm run build --workspace=packages/bruno-query
      - name: Test Package bruno-lang
        run: npm run test --workspace=packages/bruno-lang
      - name: Test Package bruno-schema
        run: npm run test --workspace=packages/bruno-schema
      - name: Test Package bruno-app
        run: npm run test --workspace=packages/bruno-app
      - name: Test Package bruno-js
        run: npm run test --workspace=packages/bruno-js
      - name: Test Package bruno-cli
        run: npm run test --workspace=packages/bruno-cli
      - name: Test Package bruno-electron
        run: npm run test --workspace=packages/bruno-electron

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run Prettier
        run: npm run test:prettier:web
